export const SERVICE = [
  {
    title: "Intensif",
    sup: "Rp",
    price: 650,
    sub: "rb",
    description1: "5x Pertemuan",
    description2: "@2jam/pertemuan",
    description3: "",
  },
  {
    title: "Ekonomis",
    sup: "Rp",
    price: 450,
    sub: "rb",
    description1: "2x Pertemuan",
    description2: "2jam & 3jam pertemuan",
    description3: "",
  },
  {
    title: "Intensif + SIM",
    sup: "Rp",
    price: 800,
    sub: "rb",
    description1: "5x Pertemuan",
    description2: "@2jam/pertemuan",
    description3: "Pembuatan SIM A",
  },
  {
    title: "Ekonomis + SIM",
    sup: "Rp",
    price: 600,
    sub: "rb",
    description1: "2x Pertemuan",
    description2: "2jam & 3jam pertemuan",
    description3: "Pembuatan SIM A",
  },
];
